### ISSUE TITLE
Action Faild:action could not be found

### ISSUE THREAD

**Issue by zhongfly** [autosuite/autocommit#5]
I found all the action using autocommit fail in step `setup job` after 9.23(according to https://github.com/Apocalypsor/now-subconverter/actions)
You can see detail log in  https://github.com/Apocalypsor/now-subconverter/runs/1165710503
I hope to get your help.

**Comment by paced** [comment]
Hi @zhongfly, thank you for the bug report. It appears that this is happening because I renamed the main branch from `master` to `main`. I was under the impression that GitHub would automatically direct from `master` to `main` with Actions but it seems like that is not yet the case.

If you change the reference for the action to `main` or `09aa65a2345e067cdb349893e2202f57cc3ede9e` I believe it should work again. If it doesn't, please re-open this ticket.

Note that this Action is pre-release, so there may be a bit of instability.
